# Generated by Django 5.2.4 on 2025-07-08 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('grades', models.PositiveIntegerField(blank=True, null=True, verbose_name='Grades')),
                ('target', models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Учитель')], max_length=20, verbose_name='Для кого')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('file', models.FileField(upload_to='books/', verbose_name='Файл книги')),
            ],
        ),
        migrations.CreateModel(
            name='BookAudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('audio_tag', models.DecimalField(decimal_places=1, max_digits=3)),
                ('order', models.PositiveIntegerField()),
                ('audio_file', models.FileField(upload_to='audios/')),
                ('audio_type', models.CharField(choices=[('main', 'Основное'), ('repeat', 'Повторение')], default='main', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='audiobook.electronicbook')),
            ],
        ),
    ]
